### PR TITLE
Bug fixes, code improvements.

### PR DESCRIPTION
**Pull request by berkaycatak**
Back, menu and reply buttons have been made optional.
Code improvement has been made.
Errors have been corrected.

for: https://github.com/AdnanKhan45/flutter-story-view/issues/4

### CODE REVIEW

**Comment by TheGodOfTheNewWorld** [comment]
@AdnanKhan45 Please merge this one. We want all this stuff to be optional. Thanks.

**Comment by berkaycatak** [comment]
> @AdnanKhan45 Please merge this one. We want all this stuff to be optional. Thanks.

Hello @KarlMathuthu, you can add the following lines to the pubspec.yaml file and use the version I edited. I have no idea why the package owner still hasn't approved the version. It's a miracle that it's even listed on pub.dev like this.

```
  flutter_story_view:
    git:
      url: https://github.com/berkaycatak/flutter-story-view.git
      ref: main

```

**Comment by TheGodOfTheNewWorld** [comment]
> > @AdnanKhan45 Please merge this one. We want all this stuff to be optional. Thanks.
> 
> Hello @KarlMathuthu, you can add the following lines to the pubspec.yaml file and use the version I edited. I have no idea why the package owner still hasn't approved the version. It's a miracle that it's even listed on pub.dev like this.
> 
> ```
>   flutter_story_view:
>     git:
>       url: https://github.com/berkaycatak/flutter-story-view.git
>       ref: main
> ```

Thanks very much

**Review by AdnanKhan45 — COMMENTED** [review]
Hello, I'm sorry for late response. After reviewing flutter_story_view.dart you did a great job by adding documentation to the fields, you added const that's perfect but I'm wondering why "Previous story area" has been removed. Its a valid functionality in a story, we should allow users to go back to the stories already viewed. Please response on this change and verify as soon as possible to make it easy for me to merge the PR. Thank you.

**Review by AdnanKhan45 — COMMENTED** [review]
story_text.dart has been added and is not used in the main (in flutter_story_view.dart) code but instead kept commented out. Please complete this functionality so that I can merge your code.

**Comment by AdnanKhan45** [comment]
Lastly, your code does a great job, but I'd recommend to confirm these changes to make it easy to merge this PR.

**Comment by berkaycatak** [comment]
> Hello, I'm sorry for late response. After reviewing flutter_story_view.dart you did a great job by adding documentation to the fields, you added const that's perfect but I'm wondering why "Previous story area" has been removed. Its a valid functionality in a story, we should allow users to go back to the stories already viewed. Please response on this change and verify as soon as possible to make it easy for me to merge the PR. Thank you.

Hello @AdnanKhan45 ,  there was confusion during the diff phase. Return to previous story function works. That's why I added comment line. You can review it again.

> story_text.dart has been added and is not used in the main (in flutter_story_view.dart) code but instead kept commented out. Please complete this functionality so that I can merge your code.

I was going to create only text for stories without visuals, but the code structure does not allow this. I did not delete the text codes in case anyone wants to support.

**Comment by AdnanKhan45** [comment]
@berkaycatak okay great, I cloned your forked project and tested it in the app. Surprisingly, the previous area tap works 😄. Additionally, while testing the functionality I figured out that the ```showMenuIcon``` is kept true by default and user info has been made optional and the menu icon should supposed to be aligned at the right most which is not when the user info is optional so you need to take care of that also by checking one more condition for example where you checked:

```if (widget.userInfo != null) ...[ ```

in the else condition you can do something like:

``` else Expanded(child: Container())```

So in both cases the menu icon would remain at the right most. Next you changed the ```StoryItemType``` class to an enum and you're dealing with its values. We can add more flexibility to this by having an extension and do the conversion between string representation and enum values, so it will also allow dealing with database primitive data types. Add this to the story_tiem.dart

```
extension StoryItemTypeExtension on StoryItemType {
  String get name => toString().split('.').last;

  static StoryItemType fromString(String name) {
    return StoryItemType.values.firstWhere((e) => e.name == name);
  }
}
```

Lastly, for the text story I'll deal with it myself. And your other code looks good enough. So please review the changes above and then I'll merge this PR. And for the further new features in the package feel free to create any issues and doing PRs. Thank you.

**Comment by AdnanKhan45** [comment]
I have merged you PR. Please take a look at the issues I suggested above and fix them. After that I'll add you as package maintainer in the pub.dev. And if you think we can do more improvement in it so feel free to do it. Thanks @berkaycatak

**Pull request merged**
